export const Url={
    login : "",
    signup : "",
    otp:"",
    statistics:"",
    fetchguards:"",
    addcheckpoints:"",
    fetchcheckpoints:"",
    editcheckpoints:"",
    deletecheckpoints:"",
    generate_qr:"",
    fetchroutes:"",
    addroutes:"",
    editroutes:"",
    deleteroutes:"",
    fetchpatrols:"",
    addpatrols:"",
    editpatrols:"",
    deletepatrols:"",
    fetchschedules:"",
    addschedules:"",
    editschedules:"",
    deleteschedules:"",
    insightlog:"",
    absentguardreport:"",
    incidentreport:"",
    missedcheckpointreport:"",
    fetchprofile:"",
    editprofile:"",
}