export const Url={
    login : "http://localhost:4000/api/auth/login",
    logout : "http://localhost:4000/api/auth/logout",
    signup : "",
    otp:"",
    statistics:"http://localhost:4000/api/statistics",
    fetchguards:"http://localhost:4000/api/details/guardDetails",
    addcheckpoints:"http://localhost:4000/api/setup/addCheckpoint",
    fetchcheckpoints:"http://localhost:4000/api/details/checkpointDetails",
    editcheckpoints:"http://localhost:4000/api/setup/updateCheckpoint",
    deletecheckpoints:"http://localhost:4000/api/setup/deleteCheckpoint",
    generate_qr:"http://localhost:4000/qr/generate",
    fetchroutes:"http://localhost:4000/api/details/routeDetails",
    addroutes:"",
    editroutes:"http://localhost:4000/api/setup/updateRoute",
    deleteroutes:"",
    fetchpatrols:"http://localhost:4000/api/details/patrolDetails",
    addpatrols:"http://localhost:4000/api/setup/addPatrol",
    editpatrols:"http://localhost:4000/api/setup/updatePatrol",
    deletepatrols:"http://localhost:4000/api/setup/deletePatrol",
    fetchschedules:"http://localhost:4000/api/details/scheduleDetails",
    addschedules:"http://localhost:4000/api/setup/addPatrol",
    editschedules:"",
    deleteschedules:"",
    insightlog:"",
    absentguardreport:"",
    incidentreport:"",
    missedcheckpointreport:"",
    fetchprofile:"",
    editprofile:"",
}