export const Url={
    login : "http://localhost:4000/api/auth/login",
    signup : "",
    otp:"",
    statistics:"http://localhost:4000/api/statistics",
    fetchguards:"http://localhost:4000/api/details/guardDetails",
    addcheckpoints:"http://localhost:4000/api/setup/addCheckpoint",
    fetchcheckpoints:"http://localhost:4000/api/details/checkpointDetails",
    editcheckpoints:"http://localhost:4000/api/setup/updateCheckpoint",
    deletecheckpoints:"http://localhost:4000/api/setup/deleteCheckpoint",
    generate_qr:"http://localhost:4000/qr/generate",
    fetchroutes:"http://localhost:4000/api/details/routeDetails",
    addroutes:"",
    editroutes:"http://localhost:4000/api/setup/updateRoute",
    deleteroutes:"",
    fetchpatrols:"http://localhost:4000/api/details/patrolDetails",
    addpatrols:"",
    editpatrols:"",
    deletepatrols:"",
    fetchschedules:"http://localhost:4000/api/details/scheduleDetails",
    addschedules:"",
    editschedules:"",
    deleteschedules:"",
    insightlog:"",
    absentguardreport:"",
    incidentreport:"",
    missedcheckpointreport:"",
    fetchprofile:"",
    editprofile:"",
}